### ISSUE TITLE
The v2 is a folder on main branch, not a branch. Is this ready to use and replace v1?

### ISSUE THREAD

**Issue by Yeonpyeong** [ijt/go-anytime#66]
Or maybe it's still WIP, and I should use v1 instead. A bit confused.

**Comment by ijt** [comment]
I'm pretty sure this is standard practice.

https://go.dev/blog/v2-go-modules
<img width="967" alt="Screenshot 2023-02-20 at 8 33 06 AM" src="https://user-images.githubusercontent.com/15530/220147654-69157790-5f5c-41f2-9ebc-f0c43ea8db80.png">

You can bring go-anytime/v2 into your project by running

```go get github.com/ijt/go-anytime/v2```

and importing it like this:

```go
package main

import (
	"fmt"
	"log"
	"time"

	"github.com/ijt/go-anytime/v2"
)

func main() {
	r, p, err := anytime.ParseRange("January is so cold!", time.Now(), anytime.Past)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("range start: %#v, parsed string: %q\n", r.Start().Format(time.RFC3339), p)
}
```
